### ISSUE TITLE
When creating a new category, category does not appear in scroll. Even after refreshing the page.

### ISSUE THREAD

**Issue by casal033** [casal033/WordRiver_MAP_Summer#2]

**Comment by kklamberty** [comment]
Can you say more about what you mean by "appear in scroll"? Do you mean the menu on Story Builder or something in Word River?

**Comment by casal033** [comment]
I do! The menu of categories, when there's enough categories it includes a scroll option.

**Comment by casal033** [comment]
When fixing the check for nulls in patching to server this was also fixed.
